package org.tensorflow.lite.examples.audio.helper

import org.tensorflow.lite.support.label.Category

object TextMatchingHelper {
    fun textMatch(category: Category): String{
        var label: String = ""

        // 카테고리 정보가 Speech일 경우, 화면에 "말하기소리 같습니다." 메시지를 표시
        // 카테고리 정보가 Child speech, kid speaking일 경우, 화면에 "어린이 말하기, 어린이 말하기소리 같습니다." 메시지를 표시
        // ... (여러 분류 결과에 대해 각각 메시지를 할당함)
        if(category.label.equals("Speech")){label = "말하기소리 같습니다."}
        else if(category.label.equals("Child speech, kid speaking")){label = "어린이 말하기, 어린이 말하기소리 같습니다."}
        else if(category.label.equals("Conversation")){label = "대화소리 같습니다."}
        else if(category.label.equals("Narration, monologue")){label = "내레이션, 독백소리 같습니다."}
        else if(category.label.equals("Babbling")){label = "옹알이소리 같습니다."}
        else if(category.label.equals("Speech synthesizer")){label = "음성 합성기소리 같습니다."}
        else if(category.label.equals("Shout")){label = "Shout소리 같습니다."}
        else if(category.label.equals("Bellow")){label = "Bellow소리 같습니다."}
        else if(category.label.equals("Whoop")){label = "Whoop소리 같습니다."}
        else if(category.label.equals("Yell")){label = "Yell소리 같습니다."}
        else if(category.label.equals("Children shouting")){label = "소리 지르는 어린이소리 같습니다."}
        else if(category.label.equals("Screaming")){label = "비명소리 같습니다."}
        else if(category.label.equals("Whispering")){label = "속삭이는 소리소리 같습니다."}
        else if(category.label.equals("Laughter")){label = "웃음소리소리 같습니다."}
        else if(category.label.equals("Baby laughter")){label = "아기 웃음소리 같습니다."}
        else if(category.label.equals("Giggle")){label = "낄낄거리기소리 같습니다."}
        else if(category.label.equals("Snicker")){label = "스니커소리 같습니다."}
        else if(category.label.equals("Belly laugh")){label = "배꼽 웃음소리 같습니다."}
        else if(category.label.equals("Chuckle, chortle")){label = "낄낄, 낄낄소리 같습니다."}
        else if(category.label.equals("Crying, sobbing")){label = "울음, 흐느낌소리 같습니다."}
        else if(category.label.equals("Baby cry, infant cry")){label = "아기 울음, 유아 울음소리 같습니다."}
        else if(category.label.equals("Whimper")){label = "Whimper소리 같습니다."}
        else if(category.label.equals("Wail, moan")){label = "울음, 신음소리 같습니다."}
        else if(category.label.equals("Sigh")){label = "한숨소리 같습니다."}
        else if(category.label.equals("Singing")){label = "노래소리 같습니다."}
        else if(category.label.equals("Choir")){label = "합창단소리 같습니다."}
        else if(category.label.equals("Yodeling")){label = "요들송소리 같습니다."}
        else if(category.label.equals("Chant")){label = "Chant소리 같습니다."}
        else if(category.label.equals("Mantra")){label = "만트라소리 같습니다."}
        else if(category.label.equals("Child singing")){label = "어린이 노래소리 같습니다."}
        else if(category.label.equals("Synthetic singing")){label = "합성 노래소리 같습니다."}
        else if(category.label.equals("Rapping")){label = "랩소리 같습니다."}
        else if(category.label.equals("Humming")){label = "허밍소리 같습니다."}
        else if(category.label.equals("Groan")){label = "Groan소리 같습니다."}
        else if(category.label.equals("Grunt")){label = "Grunt소리 같습니다."}
        else if(category.label.equals("Whistling")){label = "휘파람소리 같습니다."}
        else if(category.label.equals("Breathing")){label = "호흡소리 같습니다."}
        else if(category.label.equals("Wheeze")){label = "Wheeze소리 같습니다."}
        else if(category.label.equals("Snoring")){label = "코골이소리 같습니다."}
        else if(category.label.equals("Gasp")){label = "Gasp소리 같습니다."}
        else if(category.label.equals("Pant")){label = "헐떡거림소리 같습니다."}
        else if(category.label.equals("Snort")){label = "Snort소리 같습니다."}
        else if(category.label.equals("Cough")){label = "Cough소리 같습니다."}
        else if(category.label.equals("Throat clearing")){label = "인후통소리 같습니다."}
        else if(category.label.equals("Sneeze")){label = "재채기소리 같습니다."}
        else if(category.label.equals("Sniff")){label = "Sniff소리 같습니다."}
        else if(category.label.equals("Run")){label = "Run소리 같습니다."}
        else if(category.label.equals("Shuffle")){label = "셔플소리 같습니다."}
        else if(category.label.equals("Walk, footsteps")){label = "걷기, 발걸음소리 같습니다."}
        else if(category.label.equals("Chewing, mastication")){label = "씹기, 저작소리 같습니다."}
        else if(category.label.equals("Biting")){label = "물기소리 같습니다."}
        else if(category.label.equals("Gargling")){label = "양치질소리 같습니다."}
        else if(category.label.equals("Stomach rumble")){label = "복부 럼블소리 같습니다."}
        else if(category.label.equals("Burping, eructation")){label = "트림, 사정소리 같습니다."}
        else if(category.label.equals("Hiccup")){label = "딸꾹질소리 같습니다."}
        else if(category.label.equals("Fart")){label = "방귀소리 같습니다."}
        else if(category.label.equals("Hands")){label = "손소리 같습니다."}
        else if(category.label.equals("Finger snapping")){label = "손가락 스냅소리 같습니다."}
        else if(category.label.equals("Clapping")){label = "박수 소리소리 같습니다."}
        else if(category.label.equals("Heart sounds, heartbeat")){label = "심장 소리, 심장 박동소리 같습니다."}
        else if(category.label.equals("Heart murmur")){label = "심장 잡음소리 같습니다."}
        else if(category.label.equals("Cheering")){label = "응원소리 같습니다."}
        else if(category.label.equals("Applause")){label = "박수소리 같습니다."}
        else if(category.label.equals("Chatter")){label = "수다소리 같습니다."}
        else if(category.label.equals("Crowd")){label = "군중소리 같습니다."}
        else if(category.label.equals("Hubbub, speech noise, speech babble")){label = "윙윙거리는 소리, 말소리, 옹알이 소리소리 같습니다."}
        else if(category.label.equals("Children playing")){label = "노는 아이들소리 같습니다."}
        else if(category.label.equals("Animal")){label = "동물소리 같습니다."}
        else if(category.label.equals("Domestic animals, pets")){label = "가축, 애완동물소리 같습니다."}
        else if(category.label.equals("Dog")){label = "개소리 같습니다."}
        else if(category.label.equals("Bark")){label = "Bark소리 같습니다."}
        else if(category.label.equals("Yip")){label = "Yip소리 같습니다."}
        else if(category.label.equals("Howl")){label = "Howl소리 같습니다."}
        else if(category.label.equals("Bow-wow")){label = "Bow-wow소리 같습니다."}
        else if(category.label.equals("Growling")){label = "Growling소리 같습니다."}
        else if(category.label.equals("Whimper (dog)")){label = "윙윙(개)소리 같습니다."}
        else if(category.label.equals("Cat")){label = "고양이소리 같습니다."}
        else if(category.label.equals("Purr")){label = "Purr소리 같습니다."}
        else if(category.label.equals("Meow")){label = "Meow소리 같습니다."}
        else if(category.label.equals("Hiss")){label = "Hiss소리 같습니다."}
        else if(category.label.equals("Caterwaul")){label = "Caterwaul소리 같습니다."}
        else if(category.label.equals("Livestock, farm animals, working animals")){label = "가축, 농장 동물, 일하는 동물소리 같습니다."}
        else if(category.label.equals("Horse")){label = "말소리 같습니다."}
        else if(category.label.equals("Clip-clop")){label = "클립-클롭소리 같습니다."}
        else if(category.label.equals("Neigh, whinny")){label = "이웃, 우는 소리소리 같습니다."}
        else if(category.label.equals("Cattle, bovinae")){label = "소, 소소리 같습니다."}
        else if(category.label.equals("Moo")){label = "Moo소리 같습니다."}
        else if(category.label.equals("Cowbell")){label = "Cowbell소리 같습니다."}
        else if(category.label.equals("Pig")){label = "Pig소리 같습니다."}
        else if(category.label.equals("Oink")){label = "Oink소리 같습니다."}
        else if(category.label.equals("Goat")){label = "Goat소리 같습니다."}
        else if(category.label.equals("Bleat")){label = "Bleat소리 같습니다."}
        else if(category.label.equals("Sheep")){label = "Sheep소리 같습니다."}
        else if(category.label.equals("Fowl")){label = "Fowl소리 같습니다."}
        else if(category.label.equals("Chicken, rooster")){label = "닭, 수탉소리 같습니다."}
        else if(category.label.equals("Cluck")){label = "Cluck소리 같습니다."}
        else if(category.label.equals("Crowing, cock-a-doodle-doo")){label = "울음소리, 두두두두소리 같습니다."}
        else if(category.label.equals("Turkey")){label = "칠면조소리 같습니다."}
        else if(category.label.equals("Gobble")){label = "Gobble소리 같습니다."}
        else if(category.label.equals("Duck")){label = "Duck소리 같습니다."}
        else if(category.label.equals("Quack")){label = "Quack소리 같습니다."}
        else if(category.label.equals("Goose")){label = "Goose소리 같습니다."}
        else if(category.label.equals("Honk")){label = "Honk소리 같습니다."}
        else if(category.label.equals("Wild animals")){label = "야생 동물소리 같습니다."}
        else if(category.label.equals("Roaring cats (lions, tigers)")){label = "포효하는 고양이(사자, 호랑이)소리 같습니다."}
        else if(category.label.equals("Roar")){label = "Roar소리 같습니다."}
        else if(category.label.equals("Bird")){label = "Bird소리 같습니다."}
        else if(category.label.equals("Bird vocalization, bird call, bird song")){label = "새 발성, 새 울음소리, 새 노래소리 같습니다."}
        else if(category.label.equals("Chirp, tweet")){label = "지저귀는 소리, 지저귀는 소리소리 같습니다."}
        else if(category.label.equals("Squawk")){label = "스쿼크소리 같습니다."}
        else if(category.label.equals("Pigeon, dove")){label = "비둘기, 비둘기소리 같습니다."}
        else if(category.label.equals("Coo")){label = "Coo소리 같습니다."}
        else if(category.label.equals("Crow")){label = "까마귀소리 같습니다."}
        else if(category.label.equals("Caw")){label = "Caw소리 같습니다."}
        else if(category.label.equals("Owl")){label = "Owl소리 같습니다."}
        else if(category.label.equals("Hoot")){label = "Hoot소리 같습니다."}
        else if(category.label.equals("Bird flight, flapping wings")){label = "새의 비행, 날갯짓소리 같습니다."}
        else if(category.label.equals("Canidae, dogs, wolves")){label = "개과 동물, 개, 늑대소리 같습니다."}
        else if(category.label.equals("Rodents, rats, mice")){label = "설치류, 쥐, 생쥐소리 같습니다."}
        else if(category.label.equals("Mouse")){label = "마우스소리 같습니다."}
        else if(category.label.equals("Patter")){label = "Patter소리 같습니다."}
        else if(category.label.equals("Insect")){label = "곤충소리 같습니다."}
        else if(category.label.equals("Cricket")){label = "크리켓소리 같습니다."}
        else if(category.label.equals("Mosquito")){label = "모기소리 같습니다."}
        else if(category.label.equals("Fly, housefly")){label = "파리, 집파리소리 같습니다."}
        else if(category.label.equals("Buzz")){label = "Buzz소리 같습니다."}
        else if(category.label.equals("Bee, wasp, etc.")){label = "벌, 말벌 등소리 같습니다."}
        else if(category.label.equals("Frog")){label = "개구리소리 같습니다."}
        else if(category.label.equals("Croak")){label = "Croak소리 같습니다."}
        else if(category.label.equals("Snake")){label = "뱀소리 같습니다."}
        else if(category.label.equals("Rattle")){label = "딸랑이소리 같습니다."}
        else if(category.label.equals("Whale vocalization")){label = "고래 발성소리 같습니다."}
        else if(category.label.equals("Music")){label = "음악소리 같습니다."}
        else if(category.label.equals("Musical instrument")){label = "악기소리 같습니다."}
        else if(category.label.equals("Plucked string instrument")){label = "현악기소리 같습니다."}
        else if(category.label.equals("Guitar")){label = "기타소리 같습니다."}
        else if(category.label.equals("Electric guitar")){label = "일렉트릭 기타소리 같습니다."}
        else if(category.label.equals("Bass guitar")){label = "베이스 기타소리 같습니다."}
        else if(category.label.equals("Acoustic guitar")){label = "어쿠스틱 기타소리 같습니다."}
        else if(category.label.equals("Steel guitar, slide guitar")){label = "스틸 기타, 슬라이드 기타소리 같습니다."}
        else if(category.label.equals("Tapping (guitar technique)")){label = "탭핑(기타 테크닉)소리 같습니다."}
        else if(category.label.equals("Strum")){label = "스트럼소리 같습니다."}
        else if(category.label.equals("Banjo")){label = "밴조소리 같습니다."}
        else if(category.label.equals("Sitar")){label = "Sitar소리 같습니다."}
        else if(category.label.equals("Mandolin")){label = "만돌린소리 같습니다."}
        else if(category.label.equals("Zither")){label = "Zither소리 같습니다."}
        else if(category.label.equals("Ukulele")){label = "우쿨렐레소리 같습니다."}
        else if(category.label.equals("Keyboard (musical)")){label = "키보드(뮤지컬)소리 같습니다."}
        else if(category.label.equals("Piano")){label = "피아노소리 같습니다."}
        else if(category.label.equals("Electric piano")){label = "일렉트릭 피아노소리 같습니다."}
        else if(category.label.equals("Organ")){label = "오르간소리 같습니다."}
        else if(category.label.equals("Electronic organ")){label = "전자 오르간소리 같습니다."}
        else if(category.label.equals("Hammond organ")){label = "해먼드 오르간소리 같습니다."}
        else if(category.label.equals("Synthesizer")){label = "신디사이저소리 같습니다."}
        else if(category.label.equals("Sampler")){label = "샘플러소리 같습니다."}
        else if(category.label.equals("Harpsichord")){label = "하프시코드소리 같습니다."}
        else if(category.label.equals("Percussion")){label = "퍼커션소리 같습니다."}
        else if(category.label.equals("Drum kit")){label = "드럼 키트소리 같습니다."}
        else if(category.label.equals("Drum machine")){label = "드럼 머신소리 같습니다."}
        else if(category.label.equals("Drum")){label = "드럼소리 같습니다."}
        else if(category.label.equals("Snare drum")){label = "스네어 드럼소리 같습니다."}
        else if(category.label.equals("Rimshot")){label = "림샷소리 같습니다."}
        else if(category.label.equals("Drum roll")){label = "드럼 롤소리 같습니다."}
        else if(category.label.equals("Bass drum")){label = "베이스 드럼소리 같습니다."}
        else if(category.label.equals("Timpani")){label = "팀파니소리 같습니다."}
        else if(category.label.equals("Tabla")){label = "Tabla소리 같습니다."}
        else if(category.label.equals("Cymbal")){label = "심벌즈소리 같습니다."}
        else if(category.label.equals("Hi-hat")){label = "하이햇소리 같습니다."}
        else if(category.label.equals("Wood block")){label = "우드 블록소리 같습니다."}
        else if(category.label.equals("Tambourine")){label = "탬버린소리 같습니다."}
        else if(category.label.equals("Rattle (instrument)")){label = "딸랑이(악기)소리 같습니다."}
        else if(category.label.equals("Maraca")){label = "마라카소리 같습니다."}
        else if(category.label.equals("Gong")){label = "징소리 같습니다."}
        else if(category.label.equals("Tubular bells")){label = "관형 종소리 같습니다."}
        else if(category.label.equals("Mallet percussion")){label = "말렛 타악기소리 같습니다."}
        else if(category.label.equals("Marimba, xylophone")){label = "마림바, 실로폰소리 같습니다."}
        else if(category.label.equals("Glockenspiel")){label = "글로켄슈필소리 같습니다."}
        else if(category.label.equals("Vibraphone")){label = "비브라폰소리 같습니다."}
        else if(category.label.equals("Steelpan")){label = "스틸팬소리 같습니다."}
        else if(category.label.equals("Orchestra")){label = "오케스트라소리 같습니다."}
        else if(category.label.equals("Brass instrument")){label = "금관악기소리 같습니다."}
        else if(category.label.equals("French horn")){label = "프렌치 호른소리 같습니다."}
        else if(category.label.equals("Trumpet")){label = "트럼펫소리 같습니다."}
        else if(category.label.equals("Trombone")){label = "트롬본소리 같습니다."}
        else if(category.label.equals("Bowed string instrument")){label = "활 현악기소리 같습니다."}
        else if(category.label.equals("String section")){label = "현악기 섹션소리 같습니다."}
        else if(category.label.equals("Violin, fiddle")){label = "바이올린, 바이올린소리 같습니다."}
        else if(category.label.equals("Pizzicato")){label = "피치카토소리 같습니다."}
        else if(category.label.equals("Cello")){label = "첼로소리 같습니다."}
        else if(category.label.equals("Double bass")){label = "더블베이스소리 같습니다."}
        else if(category.label.equals("Wind instrument, woodwind instrument")){label = "관악기, 목관악기소리 같습니다."}
        else if(category.label.equals("Flute")){label = "플루트소리 같습니다."}
        else if(category.label.equals("Saxophone")){label = "색소폰소리 같습니다."}
        else if(category.label.equals("Clarinet")){label = "클라리넷소리 같습니다."}
        else if(category.label.equals("Harp")){label = "하프소리 같습니다."}
        else if(category.label.equals("Bell")){label = "Bell소리 같습니다."}
        else if(category.label.equals("Church bell")){label = "교회 종소리 같습니다."}
        else if(category.label.equals("Jingle bell")){label = "징글벨소리 같습니다."}
        else if(category.label.equals("Bicycle bell")){label = "자전거 벨소리 같습니다."}
        else if(category.label.equals("Tuning fork")){label = "소리굽쇠소리 같습니다."}
        else if(category.label.equals("Chime")){label = "차임소리 같습니다."}
        else if(category.label.equals("Wind chime")){label = "바람 종소리소리 같습니다."}
        else if(category.label.equals("Change ringing (campanology)")){label = "벨소리 변경(캄파놀로)소리 같습니다."}
        else if(category.label.equals("Harmonica")){label = "하모니카소리 같습니다."}
        else if(category.label.equals("Accordion")){label = "아코디언소리 같습니다."}
        else if(category.label.equals("Bagpipes")){label = "백파이프소리 같습니다."}
        else if(category.label.equals("Didgeridoo")){label = "디저리두소리 같습니다."}
        else if(category.label.equals("Shofar")){label = "Shofar소리 같습니다."}
        else if(category.label.equals("Theremin")){label = "테레민소리 같습니다."}
        else if(category.label.equals("Singing bowl")){label = "노래하는 그릇소리 같습니다."}
        else if(category.label.equals("Scratching (performance technique)")){label = "스크래칭(연주 기법)소리 같습니다."}
        else if(category.label.equals("Pop music")){label = "팝 음악소리 같습니다."}
        else if(category.label.equals("Hip hop music")){label = "힙합 음악소리 같습니다."}
        else if(category.label.equals("Beatboxing")){label = "비트박스소리 같습니다."}
        else if(category.label.equals("Rock music")){label = "록 음악소리 같습니다."}
        else if(category.label.equals("Heavy metal")){label = "헤비메탈소리 같습니다."}
        else if(category.label.equals("Punk rock")){label = "펑크 록소리 같습니다."}
        else if(category.label.equals("Grunge")){label = "그런지소리 같습니다."}
        else if(category.label.equals("Progressive rock")){label = "프로그레시브 록소리 같습니다."}
        else if(category.label.equals("Rock and roll")){label = "로큰롤소리 같습니다."}
        else if(category.label.equals("Psychedelic rock")){label = "사이키델릭 록소리 같습니다."}
        else if(category.label.equals("Rhythm and blues")){label = "리듬 앤 블루스소리 같습니다."}
        else if(category.label.equals("Soul music")){label = "소울 음악소리 같습니다."}
        else if(category.label.equals("Reggae")){label = "레게소리 같습니다."}
        else if(category.label.equals("Country")){label = "컨트리소리 같습니다."}
        else if(category.label.equals("Swing music")){label = "스윙 음악소리 같습니다."}
        else if(category.label.equals("Bluegrass")){label = "블루그래스소리 같습니다."}
        else if(category.label.equals("Funk")){label = "Funk소리 같습니다."}
        else if(category.label.equals("Folk music")){label = "포크 음악소리 같습니다."}
        else if(category.label.equals("Middle Eastern music")){label = "중동 음악소리 같습니다."}
        else if(category.label.equals("Jazz")){label = "재즈소리 같습니다."}
        else if(category.label.equals("Disco")){label = "디스코소리 같습니다."}
        else if(category.label.equals("Classical music")){label = "클래식 음악소리 같습니다."}
        else if(category.label.equals("Opera")){label = "오페라소리 같습니다."}
        else if(category.label.equals("Electronic music")){label = "일렉트로닉 음악소리 같습니다."}
        else if(category.label.equals("House music")){label = "하우스 음악소리 같습니다."}
        else if(category.label.equals("Techno")){label = "테크노소리 같습니다."}
        else if(category.label.equals("Dubstep")){label = "덥스텝소리 같습니다."}
        else if(category.label.equals("Drum and bass")){label = "드럼 및 베이스소리 같습니다."}
        else if(category.label.equals("Electronica")){label = "일렉트로니카소리 같습니다."}
        else if(category.label.equals("Electronic dance music")){label = "일렉트로닉 댄스 음악소리 같습니다."}
        else if(category.label.equals("Ambient music")){label = "앰비언트 음악소리 같습니다."}
        else if(category.label.equals("Trance music")){label = "트랜스 음악소리 같습니다."}
        else if(category.label.equals("Music of Latin America")){label = "라틴 아메리카 음악소리 같습니다."}
        else if(category.label.equals("Salsa music")){label = "살사 음악소리 같습니다."}
        else if(category.label.equals("Flamenco")){label = "플라멩코소리 같습니다."}
        else if(category.label.equals("Blues")){label = "블루스소리 같습니다."}
        else if(category.label.equals("Music for children")){label = "어린이를 위한 음악소리 같습니다."}
        else if(category.label.equals("New-age music")){label = "뉴에이지 음악소리 같습니다."}
        else if(category.label.equals("Vocal music")){label = "성악 음악소리 같습니다."}
        else if(category.label.equals("A capella")){label = "아카펠라소리 같습니다."}
        else if(category.label.equals("Music of Africa")){label = "아프리카 음악소리 같습니다."}
        else if(category.label.equals("Afrobeat")){label = "아프로비트소리 같습니다."}
        else if(category.label.equals("Christian music")){label = "기독교 음악소리 같습니다."}
        else if(category.label.equals("Gospel music")){label = "가스펠 음악소리 같습니다."}
        else if(category.label.equals("Music of Asia")){label = "아시아 음악소리 같습니다."}
        else if(category.label.equals("Carnatic music")){label = "카르나틱 음악소리 같습니다."}
        else if(category.label.equals("Music of Bollywood")){label = "볼리우드 음악소리 같습니다."}
        else if(category.label.equals("Ska")){label = "Ska소리 같습니다."}
        else if(category.label.equals("Traditional music")){label = "전통 음악소리 같습니다."}
        else if(category.label.equals("Independent music")){label = "독립 음악소리 같습니다."}
        else if(category.label.equals("Song")){label = "노래소리 같습니다."}
        else if(category.label.equals("Background music")){label = "배경 음악소리 같습니다."}
        else if(category.label.equals("Theme music")){label = "테마 음악소리 같습니다."}
        else if(category.label.equals("Jingle (music)")){label = "징글(음악)소리 같습니다."}
        else if(category.label.equals("Soundtrack music")){label = "사운드트랙 음악소리 같습니다."}
        else if(category.label.equals("Lullaby")){label = "자장가소리 같습니다."}
        else if(category.label.equals("Video game music")){label = "비디오 게임 음악소리 같습니다."}
        else if(category.label.equals("Christmas music")){label = "크리스마스 음악소리 같습니다."}
        else if(category.label.equals("Dance music")){label = "댄스 음악소리 같습니다."}
        else if(category.label.equals("Wedding music")){label = "웨딩 음악소리 같습니다."}
        else if(category.label.equals("Happy music")){label = "행복한 음악소리 같습니다."}
        else if(category.label.equals("Sad music")){label = "슬픈 음악소리 같습니다."}
        else if(category.label.equals("Tender music")){label = "부드러운 음악소리 같습니다."}
        else if(category.label.equals("Exciting music")){label = "신나는 음악소리 같습니다."}
        else if(category.label.equals("Angry music")){label = "화난 음악소리 같습니다."}
        else if(category.label.equals("Scary music")){label = "무서운 음악소리 같습니다."}
        else if(category.label.equals("Wind")){label = "바람소리 같습니다."}
        else if(category.label.equals("Rustling leaves")){label = "바스락거리는 나뭇잎소리 같습니다."}
        else if(category.label.equals("Wind noise (microphone)")){label = "바람 소리(마이크)소리 같습니다."}
        else if(category.label.equals("Thunderstorm")){label = "천둥소리 같습니다."}
        else if(category.label.equals("Thunder")){label = "천둥소리 같습니다."}
        else if(category.label.equals("Water")){label = "물소리 같습니다."}
        else if(category.label.equals("Rain")){label = "Rain소리 같습니다."}
        else if(category.label.equals("Raindrop")){label = "빗방울소리 같습니다."}
        else if(category.label.equals("Rain on surface")){label = "표면에 내리는 비소리 같습니다."}
        else if(category.label.equals("Stream")){label = "Stream소리 같습니다."}
        else if(category.label.equals("Waterfall")){label = "폭포소리 같습니다."}
        else if(category.label.equals("Ocean")){label = "바다소리 같습니다."}
        else if(category.label.equals("Waves, surf")){label = "파도, 서핑소리 같습니다."}
        else if(category.label.equals("Steam")){label = "증기소리 같습니다."}
        else if(category.label.equals("Gurgling")){label = "졸졸소리 같습니다."}
        else if(category.label.equals("Fire")){label = "불소리 같습니다."}
        else if(category.label.equals("Crackle")){label = "Crackle소리 같습니다."}
        else if(category.label.equals("Vehicle")){label = "차량소리 같습니다."}
        else if(category.label.equals("Boat, Water vehicle")){label = "보트, 수상 차량소리 같습니다."}
        else if(category.label.equals("Sailboat, sailing ship")){label = "요트, 범선소리 같습니다."}
        else if(category.label.equals("Rowboat, canoe, kayak")){label = "노 젓는 배, 카누, 카약소리 같습니다."}
        else if(category.label.equals("Motorboat, speedboat")){label = "모터보트, 스피드 보트소리 같습니다."}
        else if(category.label.equals("Ship")){label = "선박소리 같습니다."}
        else if(category.label.equals("Motor vehicle (road)")){label = "자동차(도로)소리 같습니다."}
        else if(category.label.equals("Car")){label = "자동차소리 같습니다."}
        else if(category.label.equals("Vehicle horn, car horn, honking")){label = "차량 경적, 자동차 경적, 경적 소리소리 같습니다."}
        else if(category.label.equals("Toot")){label = "Toot소리 같습니다."}
        else if(category.label.equals("Car alarm")){label = "자동차 알람소리 같습니다."}
        else if(category.label.equals("Power windows, electric windows")){label = "파워 윈도우, 전동 윈도우소리 같습니다."}
        else if(category.label.equals("Skidding")){label = "미끄러짐소리 같습니다."}
        else if(category.label.equals("Tire squeal")){label = "타이어 삐걱거리는 소리소리 같습니다."}
        else if(category.label.equals("Car passing by")){label = "지나가는 자동차소리 같습니다."}
        else if(category.label.equals("Race car, auto racing")){label = "경주용 자동차, 자동차 경주소리 같습니다."}
        else if(category.label.equals("Truck")){label = "트럭소리 같습니다."}
        else if(category.label.equals("Air brake")){label = "에어 브레이크소리 같습니다."}
        else if(category.label.equals("Air horn, truck horn")){label = "에어 혼, 트럭 경적소리 같습니다."}
        else if(category.label.equals("Reversing beeps")){label = "후진 경고음소리 같습니다."}
        else if(category.label.equals("Ice cream truck, ice cream van")){label = "아이스크림 트럭, 아이스크림 밴소리 같습니다."}
        else if(category.label.equals("Bus")){label = "버스소리 같습니다."}
        else if(category.label.equals("Emergency vehicle")){label = "긴급 차량소리 같습니다."}
        else if(category.label.equals("Police car (siren)")){label = "경찰차(사이렌)소리 같습니다."}
        else if(category.label.equals("Ambulance (siren)")){label = "구급차(사이렌)소리 같습니다."}
        else if(category.label.equals("Fire engine, fire truck (siren)")){label = "소방차, 소방차(사이렌)소리 같습니다."}
        else if(category.label.equals("Motorcycle")){label = "오토바이소리 같습니다."}
        else if(category.label.equals("Traffic noise, roadway noise")){label = "교통 소음, 도로 소음소리 같습니다."}
        else if(category.label.equals("Rail transport")){label = "철도 운송소리 같습니다."}
        else if(category.label.equals("Train")){label = "기차소리 같습니다."}
        else if(category.label.equals("Train whistle")){label = "기차 휘파람소리 같습니다."}
        else if(category.label.equals("Train horn")){label = "기차 경적소리 같습니다."}
        else if(category.label.equals("Railroad car, train wagon")){label = "철도 차량, 기차 마차소리 같습니다."}
        else if(category.label.equals("Train wheels squealing")){label = "기차 바퀴 삐걱거리는 소리소리 같습니다."}
        else if(category.label.equals("Subway, metro, underground")){label = "지하철, 지하철, 지하소리 같습니다."}
        else if(category.label.equals("Aircraft")){label = "항공기소리 같습니다."}
        else if(category.label.equals("Aircraft engine")){label = "항공기 엔진소리 같습니다."}
        else if(category.label.equals("Jet engine")){label = "제트 엔진소리 같습니다."}
        else if(category.label.equals("Propeller, airscrew")){label = "프로펠러, 에어 스크류소리 같습니다."}
        else if(category.label.equals("Helicopter")){label = "헬리콥터소리 같습니다."}
        else if(category.label.equals("Fixed-wing aircraft, airplane")){label = "고정익 항공기, 비행기소리 같습니다."}
        else if(category.label.equals("Bicycle")){label = "자전거소리 같습니다."}
        else if(category.label.equals("Skateboard")){label = "스케이트보드소리 같습니다."}
        else if(category.label.equals("Engine")){label = "엔진소리 같습니다."}
        else if(category.label.equals("Light engine (high frequency)")){label = "라이트 엔진(고주파)소리 같습니다."}
        else {label = "무슨 소리인지 모르겠습니다."}

        return label
    }
}